.github/workflows/test-ci-prod.yaml
jest.json
package.json

__Dependencies__
__Resources__
- https://coveralls.io/
- https://coveralls.io/github/privacy-scaling-explorations
- https://github.com/marketplace/actions/coveralls-github-action

Add `coveralls` to `test-ci-prod` Github Action

---

CHANGELOG.md
RELEASE.md
lerna.json
packages/actions/CHANGELOG.md
packages/backend/CHANGELOG.md
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
yarn.lock

Release 0.3.0

---

CHANGELOG.md
lerna.json
packages/actions/CHANGELOG.md
packages/actions/package.json
packages/actions/test/unit/security.test.ts
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
yarn.lock

Publish 0.4.2

---

packages/phase2cli/src/commands/contribute.ts
packages/phase2cli/src/lib/utils.ts

added extra messages on the UI and auth checks to inform of possible reputation checks failure

fix(ux): added more verbose messages to inform the user of waiting times and errors

---

packages/backend/src/functions/circuit.ts

Add retry mechanism to VM startup

fix(vms): retry mechanism for VM startup

---

packages/phase2cli/src/commands/contribute.ts
packages/phase2cli/src/index.ts
packages/phase2cli/src/lib/errors.ts

This PR adds the ceremony and entropy options for contribute command to avoid the interactive flow. 
nb. the ceremony option should match a `ceremonyPrefix`!

Add options for `contribute` command

---

packages/phase2cli/src/commands/contribute.ts
packages/phase2cli/src/lib/utils.ts

This PR incorporate the feedbacks from the latest dry-run in terms of UX/UI improvements.

Improve UX/UI of `contribute` command

---

packages/actions/src/types/index.ts
packages/actions/test/data/artifacts/ceremonySetup.json
packages/actions/test/e2e/finalization.test.ts
packages/actions/test/unit/contribute.test.ts
packages/actions/test/unit/database.test.ts
packages/actions/test/unit/ec2.test.ts
packages/actions/test/unit/finalize.test.ts
packages/actions/test/unit/storage.test.ts

invert order of tests and remove redundant fields in the setup config file.

fix(tests and setup): fix tests and cleanup config file

---

packages/backend/src/functions/circuit.ts
packages/backend/src/functions/timeout.ts
packages/phase2cli/src/commands/auth.ts
packages/phase2cli/src/commands/contribute.ts

fix various bugs related to concurrency in serverless functions 
#131 
#127 
#114

fix(ceremony): fix various bugs

---

.github/workflows/publish-dev-packages.yaml
.github/workflows/publish-production-packages.yaml
.github/workflows/publish-staging-packages.yaml

Fix the npm publish error occurred in https://github.com/privacy-scaling-explorations/p0tion/actions/runs/5694179757

fix(publish): fix npm publish error

---

packages/actions/src/helpers/constants.ts
packages/actions/src/helpers/security.ts
packages/backend/firestore.rules
packages/backend/src/functions/user.ts

feat(auth) - fixes and optimizations

---

.github/workflows/publish-dev-packages.yaml
.github/workflows/publish-staging-packages.yaml

This PR updates the package dependencies to their latest versions and publishes dev/staging packages to the registry. The purpose of this workflow is to ensure that the latest versions of our dependencies are used in our dev and staging environments.

Update package dependencies of dev/staging packages

---

packages/actions/src/helpers/storage.ts
packages/phase2cli/src/lib/utils.ts

fix(contribution-steps) - allow more time between steps and ui improvements

---

packages/backend/src/functions/circuit.ts

fix(vm): always stop the VM even on SSM errors

---

packages/backend/src/functions/storage.ts

fix(timeout): allow larger timeout when generating signed-urls for upload

---

.github/workflows/publish-dev-packages.yaml
.github/workflows/publish-staging-packages.yaml

fix(ci): fix an issue with circular dependencies

---

README.md
packages/actions/README.md
packages/backend/README.md
packages/backend/src/lib/utils.ts
packages/phase2cli/README.md
packages/phase2cli/src/commands/observe.ts
packages/phase2cli/src/commands/setup.ts
packages/phase2cli/src/lib/prompts.ts

fix some typos in comments and docs.

fix: some typos

---

.gitignore

config files folder for jetbrains IDEs

chore(.gitignore): ignore `.idea`

---

package.json
packages/actions/test/unit/contribute.test.ts

---
---
- Fix `test` script (`test:dev` was removed in https://github.com/privacy-scaling-explorations/p0tion/commit/adf8d5e55ecddd27fc7bffdae59cbfbb1668a96d)
- Fix 2 test cases
`yarn test:dev`, 2 tests previously failing now pass.

test: fix `test` script and 2 test cases

---

packages/actions/.env.default
packages/actions/src/types/index.ts
packages/actions/test/unit/contribute.test.ts
packages/actions/test/unit/finalize.test.ts
packages/actions/test/unit/security.test.ts
packages/actions/test/unit/storage.test.ts
packages/backend/src/functions/ceremony.ts

chore: fix typos

---

packages/phase2cli/src/commands/setup.ts

Do not compute genesis zkey again if found locally for non interactive setup

feat(setup-local-keys): do not compute zkeys again 

---

.github/workflows/firebase-deploy-dev.yaml
.github/workflows/firebase-deploy-staging.yaml
.github/workflows/publish-dev-packages.yaml
.github/workflows/publish-staging-packages.yaml

Reverts privacy-scaling-explorations/p0tion#255

Revert "Sed silent"

---

.github/workflows/firebase-deploy-dev.yaml
.github/workflows/firebase-deploy-staging.yaml
.github/workflows/publish-dev-packages.yaml
.github/workflows/publish-staging-packages.yaml

Reverts privacy-scaling-explorations/p0tion#256

Revert "Revert "Sed silent""

---

README.md

docs(fix): specify functions permissions the first time

---

packages/phase2cli/src/commands/authSIWE.ts
packages/phase2cli/src/types/index.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

siwe(feat): control errors in oauth device code

---

README.md

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

redeploy firebase

---

CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
packages/phase2cli/src/commands/ceremony/listParticipants.ts
packages/phase2cli/src/commands/contribute.ts
packages/phase2cli/src/commands/finalize.ts
packages/phase2cli/src/commands/observe.ts
packages/phase2cli/src/lib/prompts.ts

---
name: List participants details
---
List the participants of a specific ceremony with their details:
```json
{
"id": "string from user doc",
"status": "string from participant doc",
"contributionStep": "string from participant doc",
"lastUpdated": "date from participant doc"
}
```
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I reviewed the [code of conduct](https://github.com/privacy-scaling-explorations/p0tion/blob/main/CODE_OF_CONDUCT.md) and …

List participants details

---

CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
packages/phase2cli/src/commands/ceremony/listParticipants.ts
packages/phase2cli/src/commands/contribute.ts
packages/phase2cli/src/commands/finalize.ts
packages/phase2cli/src/commands/observe.ts
packages/phase2cli/src/lib/prompts.ts

I am trying to do 2 things:
1. merge the list participant details (what is their id, status, contribution step, etc)
2. deploy version 1.2.1 into npm to see if the .env variables get added this time (after merging this I will send a tag push)

List participant details

---

.github/workflows/publish-on-tag-push.yaml

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

fix: use prod environment in tag npm publish workflow

---

CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
packages/phase2cli/src/commands/ceremony/listParticipants.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

1.2.2 lerna

---

CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
packages/phase2cli/src/commands/ceremony/listParticipants.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

1.2.2 with lerna

---

.github/workflows/publish-on-tag-push.yaml
CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

version 1.2.3 (correct env variables)

---

.github/workflows/publish-on-tag-push.yaml
CHANGELOG.md
lerna.json
packages/backend/CHANGELOG.md
packages/backend/package.json
packages/phase2cli/CHANGELOG.md
packages/phase2cli/package.json
packages/phase2cli/src/commands/ceremony/listParticipants.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

version 1.2.3 (correct env variables) 

---

packages/backend/src/functions/storage.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

fix: increase memory in startMultiPartUpload cloud function

---

packages/backend/src/functions/storage.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

increase memory in `startMultiPartUpload` cloud function

---

packages/backend/src/functions/ceremony.ts
packages/backend/src/functions/circuit.ts
packages/backend/src/functions/participant.ts
packages/backend/src/functions/storage.ts
packages/backend/src/functions/timeout.ts
packages/backend/src/functions/user.ts

Increase CFs memory to prevent them from running out of memory

chore: increase memory for cloud functions

---

packages/backend/src/functions/timeout.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I …

timeout - include COMPLETED

---

packages/actions/src/helpers/constants.ts

---
---
Updates PPoT file links
Fixes # 295
-   [x ] Ran s 'setup ceremony' command using the updated code in my test environment. The setup proceeded without error, and the new ppot files were placede in the ceremony's S3 folders correctly.
-   [x ] My code follows the style guidelines of this project
-   [x ] I have performed a self-review of my own code
-   [x ] I have commented my code, particularly in hard-to-understand areas
-   [x ] I have made corresponding changes to the documentation
-   [x ] My changes generate no new warnings
-   [x ] Any dependent changes have been merged and published in downstream …

Update Phase1 file links

---

packages/actions/src/helpers/vm.ts

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

fix: set tag to AWS instance volume

---

packages/api/src/auth/guard/jwt.guard.spec.ts
packages/api/src/auth/guard/jwt.guard.ts

feat: move every validation to one function

---

lerna.json
packages/actions/package.json
packages/backend/package.json
packages/phase2cli/package.json

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

Publish release 1.2.6

---

yarn.lock

---
---
-   [ ] Test A
-   [ ] Test B
-   [ ] I …

chore: updated yarn.lock

---

packages/backend/src/functions/timeout.ts

---
name: Fix timeout
about: Fix timeout
---
It looks like the timeout function is not taking the `fixedTimeWindow` correctly.
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] I have made corresponding changes to the documentation
-   [X] My changes generate no new warnings
-   [X] Any dependent changes have been merged and published in downstream modules
-   [X] I reviewed the [code of conduct](https://github.com/privacy-scaling-explorations/p0tion/blob/main/CODE_OF_CONDUCT.md) and [contributors' guide](https://github.com/privacy-scaling-explorations/p0tion/blob/main/CONTRIBUTING.md)

fix: convert to milis the whole number
